// Generated by gencpp from file ass_1/GetPositionRequest.msg
// DO NOT EDIT!


#ifndef ASS_1_MESSAGE_GETPOSITIONREQUEST_H
#define ASS_1_MESSAGE_GETPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ass_1
{
template <class ContainerAllocator>
struct GetPositionRequest_
{
  typedef GetPositionRequest_<ContainerAllocator> Type;

  GetPositionRequest_()
    : my_position_x(0.0)
    , my_position_y(0.0)  {
    }
  GetPositionRequest_(const ContainerAllocator& _alloc)
    : my_position_x(0.0)
    , my_position_y(0.0)  {
  (void)_alloc;
    }



   typedef double _my_position_x_type;
  _my_position_x_type my_position_x;

   typedef double _my_position_y_type;
  _my_position_y_type my_position_y;





  typedef boost::shared_ptr< ::ass_1::GetPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ass_1::GetPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetPositionRequest_

typedef ::ass_1::GetPositionRequest_<std::allocator<void> > GetPositionRequest;

typedef boost::shared_ptr< ::ass_1::GetPositionRequest > GetPositionRequestPtr;
typedef boost::shared_ptr< ::ass_1::GetPositionRequest const> GetPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ass_1::GetPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ass_1::GetPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ass_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ass_1::GetPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ass_1::GetPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ass_1::GetPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ass_1::GetPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ass_1::GetPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ass_1::GetPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ass_1::GetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ba0213a9ddcaa2833e00c0e4c331c63";
  }

  static const char* value(const ::ass_1::GetPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ba0213a9ddcaa28ULL;
  static const uint64_t static_value2 = 0x33e00c0e4c331c63ULL;
};

template<class ContainerAllocator>
struct DataType< ::ass_1::GetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ass_1/GetPositionRequest";
  }

  static const char* value(const ::ass_1::GetPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ass_1::GetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 my_position_x\n\
float64 my_position_y\n\
";
  }

  static const char* value(const ::ass_1::GetPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ass_1::GetPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.my_position_x);
      stream.next(m.my_position_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ass_1::GetPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ass_1::GetPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "my_position_x: ";
    Printer<double>::stream(s, indent + "  ", v.my_position_x);
    s << indent << "my_position_y: ";
    Printer<double>::stream(s, indent + "  ", v.my_position_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASS_1_MESSAGE_GETPOSITIONREQUEST_H
